// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef _ESP32_UI_H
#define _ESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen7.h"
#include "screens/ui_Screen8.h"
#include "screens/ui_Screen9.h"
#include "screens/ui_Screen10.h"
#include "screens/ui_Screen11.h"
#include "screens/ui_ScreenCalc.h"
#include "screens/ui_uiScreenCalendar.h"
#include "screens/ui_uiScreenHealth.h"
#include "screens/ui_Screen12.h"
#include "screens/ui_Screen13.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_e4a23ca26f23a822_png);    // assets/e4a23ca26f23a822.png
LV_IMG_DECLARE(ui_img_a114c406157c7bb0_png);    // assets/a114c406157c7bb0.png
LV_IMG_DECLARE(ui_img_heart_pulse_icon_125258_png);    // assets/heart_pulse_icon_125258.png
LV_IMG_DECLARE(ui_img_2069392035);    // assets/1904656-calendar-date-day-event-organization-schedule-time_122506.png
LV_IMG_DECLARE(ui_img_148025d2b9cdfa08_png);    // assets/148025d2b9cdfa08.png
LV_IMG_DECLARE(ui_img_613797003);    // assets/wondicon-ui-free-calculator_111257.png
LV_IMG_DECLARE(ui_img_progress_in_status_ai_icon_215433_png);    // assets/progress_in_status_ai_icon_215433.png
LV_IMG_DECLARE(ui_img_compas_icon_176651_png);    // assets/compas_icon_176651.png
LV_IMG_DECLARE(ui_img_880976351);    // assets/罗盘刻度.png
LV_IMG_DECLARE(ui_img_1999394341);    // assets/指针 (2).png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
