// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onSyncTimeClicked(lv_event_t * e);
void onDeleteClicked(lv_event_t * e);
void onAlarmSwitchToggled(lv_event_t * e);
void onAddOkClicked(lv_event_t * e);
void onWifiSwitchToggle(lv_event_t * e);
void WifiDropdownChanged(lv_event_t * e);
void PasswordBtnClicked(lv_event_t * e);
void wifirefresh(lv_event_t * e);
void WifiConnectAction(lv_event_t * e);
void WifiCancelConnect(lv_event_t * e);
void CheckWeather(lv_event_t * e);
void onTimerStartClicked(lv_event_t * e);
void onTimerCheckClicked(lv_event_t * e);
void onTimerBackClicked(lv_event_t * e);
void onTimerStopClicked(lv_event_t * e);
void onTimerResetClicked(lv_event_t * e);
void onCalcButtonClicked(lv_event_t * e);
void onHealthSwitchChanged(lv_event_t * e);
void onNewChatClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
