// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREEN12_H
#define UI_SCREEN12_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen12
extern void ui_Screen12_screen_init(void);
extern void ui_Screen12_screen_destroy(void);
extern lv_obj_t * ui_Screen12;
extern lv_obj_t * ui_PanelAIChat;
extern lv_obj_t * ui_LabelAIText;
extern void ui_event_Button29(lv_event_t * e);
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label68;
extern void ui_event_BtnNewChat(lv_event_t * e);
extern lv_obj_t * ui_BtnNewChat;
extern lv_obj_t * ui_Label69;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

