// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREEN10_H
#define UI_SCREEN10_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen10
extern void ui_Screen10_screen_init(void);
extern void ui_Screen10_screen_destroy(void);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image5;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label24;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

