// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_AlarmListPanel = NULL;
lv_obj_t * ui_AlarmCard1 = NULL;
lv_obj_t * ui_AlarmTime1 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_AlarmSwitch1 = NULL;
lv_obj_t * ui_AlarmCard2 = NULL;
lv_obj_t * ui_AlarmTime2 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_AlarmSwitch2 = NULL;
lv_obj_t * ui_AlarmCard3 = NULL;
lv_obj_t * ui_AlarmTime3 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_AlarmSwitch3 = NULL;
lv_obj_t * ui_AlarmCard4 = NULL;
lv_obj_t * ui_AlarmTime4 = NULL;
lv_obj_t * ui_Button19 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_AlarmSwitch4 = NULL;
lv_obj_t * ui_AlarmCard5 = NULL;
lv_obj_t * ui_AlarmTime5 = NULL;
lv_obj_t * ui_Button20 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_AlarmSwitch5 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_PopupAdd = NULL;
lv_obj_t * ui_PopupBox = NULL;
lv_obj_t * ui_Roller4 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Roller5 = NULL;
lv_obj_t * ui_Button21 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_Button22 = NULL;
lv_obj_t * ui_Label39 = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen11, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 100, &ui_Screen11_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PopupAdd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onDeleteClicked(e);
    }
}

void ui_event_AlarmSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onAlarmSwitchToggled(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onDeleteClicked(e);
    }
}

void ui_event_AlarmSwitch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onAlarmSwitchToggled(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onDeleteClicked(e);
    }
}

void ui_event_AlarmSwitch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onAlarmSwitchToggled(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onDeleteClicked(e);
    }
}

void ui_event_AlarmSwitch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onAlarmSwitchToggled(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onDeleteClicked(e);
    }
}

void ui_event_AlarmSwitch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onAlarmSwitchToggled(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen8_screen_init);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PopupAdd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onAddOkClicked(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xF0F4F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 3);
    lv_obj_set_y(ui_Label7, 11);
    lv_label_set_text(ui_Label7, "CLOCK");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button5, 42);
    lv_obj_set_height(ui_Button5, 41);
    lv_obj_set_x(ui_Button5, -11);
    lv_obj_set_y(ui_Button5, 1);
    lv_obj_set_align(ui_Button5, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 87);
    lv_obj_set_y(ui_Label8, -121);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "+");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmListPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_AlarmListPanel, lv_pct(100));
    lv_obj_set_height(ui_AlarmListPanel, lv_pct(69));
    lv_obj_set_x(ui_AlarmListPanel, 2);
    lv_obj_set_y(ui_AlarmListPanel, 3);
    lv_obj_set_align(ui_AlarmListPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AlarmListPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AlarmListPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_AlarmListPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlarmListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmListPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AlarmListPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AlarmListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmCard1 = lv_obj_create(ui_AlarmListPanel);
    lv_obj_set_height(ui_AlarmCard1, 50);
    lv_obj_set_width(ui_AlarmCard1, lv_pct(105));
    lv_obj_set_x(ui_AlarmCard1, -7);
    lv_obj_set_y(ui_AlarmCard1, -60);
    lv_obj_set_align(ui_AlarmCard1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_AlarmCard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AlarmCard1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmCard1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmCard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmCard1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AlarmCard1, lv_color_hex(0xC0C9F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AlarmCard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AlarmCard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlarmCard1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AlarmCard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AlarmCard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmTime1 = lv_label_create(ui_AlarmCard1);
    lv_obj_set_width(ui_AlarmTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmTime1, -4);
    lv_obj_set_y(ui_AlarmTime1, -2);
    lv_obj_set_align(ui_AlarmTime1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmTime1, "TIME");
    lv_obj_set_style_text_font(ui_AlarmTime1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_AlarmCard1);
    lv_obj_set_width(ui_Button15, 32);
    lv_obj_set_height(ui_Button15, 29);
    lv_obj_set_x(ui_Button15, 8);
    lv_obj_set_y(ui_Button15, -1);
    lv_obj_set_align(ui_Button15, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button15, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_AlarmCard1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 87);
    lv_obj_set_y(ui_Label27, 1);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "X");

    ui_AlarmSwitch1 = lv_switch_create(ui_AlarmCard1);
    lv_obj_set_width(ui_AlarmSwitch1, 41);
    lv_obj_set_height(ui_AlarmSwitch1, 25);
    lv_obj_set_x(ui_AlarmSwitch1, 38);
    lv_obj_set_y(ui_AlarmSwitch1, 1);
    lv_obj_set_align(ui_AlarmSwitch1, LV_ALIGN_CENTER);

    ui_AlarmCard2 = lv_obj_create(ui_AlarmListPanel);
    lv_obj_set_height(ui_AlarmCard2, 50);
    lv_obj_set_width(ui_AlarmCard2, lv_pct(105));
    lv_obj_set_x(ui_AlarmCard2, -7);
    lv_obj_set_y(ui_AlarmCard2, -60);
    lv_obj_set_align(ui_AlarmCard2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_AlarmCard2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AlarmCard2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmCard2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmCard2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmCard2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AlarmCard2, lv_color_hex(0xC0C9F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AlarmCard2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AlarmCard2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlarmCard2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AlarmCard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AlarmCard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmTime2 = lv_label_create(ui_AlarmCard2);
    lv_obj_set_width(ui_AlarmTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmTime2, -4);
    lv_obj_set_y(ui_AlarmTime2, -2);
    lv_obj_set_align(ui_AlarmTime2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmTime2, "TIME");
    lv_obj_set_style_text_font(ui_AlarmTime2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_AlarmCard2);
    lv_obj_set_width(ui_Button17, 32);
    lv_obj_set_height(ui_Button17, 29);
    lv_obj_set_x(ui_Button17, 8);
    lv_obj_set_y(ui_Button17, -1);
    lv_obj_set_align(ui_Button17, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button17, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_AlarmCard2);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 87);
    lv_obj_set_y(ui_Label30, 1);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "X");

    ui_AlarmSwitch2 = lv_switch_create(ui_AlarmCard2);
    lv_obj_set_width(ui_AlarmSwitch2, 41);
    lv_obj_set_height(ui_AlarmSwitch2, 25);
    lv_obj_set_x(ui_AlarmSwitch2, 38);
    lv_obj_set_y(ui_AlarmSwitch2, 1);
    lv_obj_set_align(ui_AlarmSwitch2, LV_ALIGN_CENTER);

    ui_AlarmCard3 = lv_obj_create(ui_AlarmListPanel);
    lv_obj_set_height(ui_AlarmCard3, 50);
    lv_obj_set_width(ui_AlarmCard3, lv_pct(105));
    lv_obj_set_x(ui_AlarmCard3, -7);
    lv_obj_set_y(ui_AlarmCard3, -60);
    lv_obj_set_align(ui_AlarmCard3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_AlarmCard3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AlarmCard3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmCard3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmCard3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmCard3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AlarmCard3, lv_color_hex(0xC0C9F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AlarmCard3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AlarmCard3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlarmCard3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AlarmCard3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AlarmCard3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmTime3 = lv_label_create(ui_AlarmCard3);
    lv_obj_set_width(ui_AlarmTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmTime3, -4);
    lv_obj_set_y(ui_AlarmTime3, -2);
    lv_obj_set_align(ui_AlarmTime3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmTime3, "TIME");
    lv_obj_set_style_text_font(ui_AlarmTime3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_btn_create(ui_AlarmCard3);
    lv_obj_set_width(ui_Button18, 32);
    lv_obj_set_height(ui_Button18, 29);
    lv_obj_set_x(ui_Button18, 8);
    lv_obj_set_y(ui_Button18, -1);
    lv_obj_set_align(ui_Button18, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button18, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_AlarmCard3);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 87);
    lv_obj_set_y(ui_Label32, 1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "X");

    ui_AlarmSwitch3 = lv_switch_create(ui_AlarmCard3);
    lv_obj_set_width(ui_AlarmSwitch3, 41);
    lv_obj_set_height(ui_AlarmSwitch3, 25);
    lv_obj_set_x(ui_AlarmSwitch3, 38);
    lv_obj_set_y(ui_AlarmSwitch3, 1);
    lv_obj_set_align(ui_AlarmSwitch3, LV_ALIGN_CENTER);

    ui_AlarmCard4 = lv_obj_create(ui_AlarmListPanel);
    lv_obj_set_height(ui_AlarmCard4, 50);
    lv_obj_set_width(ui_AlarmCard4, lv_pct(105));
    lv_obj_set_x(ui_AlarmCard4, -7);
    lv_obj_set_y(ui_AlarmCard4, -60);
    lv_obj_set_align(ui_AlarmCard4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_AlarmCard4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AlarmCard4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmCard4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmCard4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmCard4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AlarmCard4, lv_color_hex(0xC0C9F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AlarmCard4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AlarmCard4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlarmCard4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AlarmCard4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AlarmCard4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmTime4 = lv_label_create(ui_AlarmCard4);
    lv_obj_set_width(ui_AlarmTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmTime4, -4);
    lv_obj_set_y(ui_AlarmTime4, -2);
    lv_obj_set_align(ui_AlarmTime4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmTime4, "TIME");
    lv_obj_set_style_text_font(ui_AlarmTime4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_AlarmCard4);
    lv_obj_set_width(ui_Button19, 32);
    lv_obj_set_height(ui_Button19, 29);
    lv_obj_set_x(ui_Button19, 8);
    lv_obj_set_y(ui_Button19, -1);
    lv_obj_set_align(ui_Button19, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button19, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_AlarmCard4);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 87);
    lv_obj_set_y(ui_Label34, 1);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "X");

    ui_AlarmSwitch4 = lv_switch_create(ui_AlarmCard4);
    lv_obj_set_width(ui_AlarmSwitch4, 41);
    lv_obj_set_height(ui_AlarmSwitch4, 25);
    lv_obj_set_x(ui_AlarmSwitch4, 38);
    lv_obj_set_y(ui_AlarmSwitch4, 1);
    lv_obj_set_align(ui_AlarmSwitch4, LV_ALIGN_CENTER);

    ui_AlarmCard5 = lv_obj_create(ui_AlarmListPanel);
    lv_obj_set_height(ui_AlarmCard5, 50);
    lv_obj_set_width(ui_AlarmCard5, lv_pct(105));
    lv_obj_set_x(ui_AlarmCard5, -7);
    lv_obj_set_y(ui_AlarmCard5, -60);
    lv_obj_set_align(ui_AlarmCard5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_AlarmCard5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AlarmCard5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmCard5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmCard5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmCard5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AlarmCard5, lv_color_hex(0xC0C9F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AlarmCard5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AlarmCard5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlarmCard5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AlarmCard5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AlarmCard5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmTime5 = lv_label_create(ui_AlarmCard5);
    lv_obj_set_width(ui_AlarmTime5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmTime5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmTime5, -4);
    lv_obj_set_y(ui_AlarmTime5, -2);
    lv_obj_set_align(ui_AlarmTime5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmTime5, "TIME");
    lv_obj_set_style_text_font(ui_AlarmTime5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button20 = lv_btn_create(ui_AlarmCard5);
    lv_obj_set_width(ui_Button20, 32);
    lv_obj_set_height(ui_Button20, 29);
    lv_obj_set_x(ui_Button20, 8);
    lv_obj_set_y(ui_Button20, -1);
    lv_obj_set_align(ui_Button20, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button20, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_AlarmCard5);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 87);
    lv_obj_set_y(ui_Label36, 1);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "X");

    ui_AlarmSwitch5 = lv_switch_create(ui_AlarmCard5);
    lv_obj_set_width(ui_AlarmSwitch5, 41);
    lv_obj_set_height(ui_AlarmSwitch5, 25);
    lv_obj_set_x(ui_AlarmSwitch5, 38);
    lv_obj_set_y(ui_AlarmSwitch5, 1);
    lv_obj_set_align(ui_AlarmSwitch5, LV_ALIGN_CENTER);

    ui_Button16 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button16, 63);
    lv_obj_set_height(ui_Button16, 33);
    lv_obj_set_x(ui_Button16, 19);
    lv_obj_set_y(ui_Button16, -118);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 19);
    lv_obj_set_y(ui_Label28, -117);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "BACK");

    ui_PopupAdd = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PopupAdd, lv_pct(100));
    lv_obj_set_height(ui_PopupAdd, lv_pct(100));
    lv_obj_set_align(ui_PopupAdd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PopupAdd, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PopupAdd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PopupAdd, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PopupAdd, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PopupAdd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopupBox = lv_obj_create(ui_PopupAdd);
    lv_obj_set_width(ui_PopupBox, lv_pct(80));
    lv_obj_set_height(ui_PopupBox, lv_pct(60));
    lv_obj_set_align(ui_PopupBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PopupBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PopupBox, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PopupBox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PopupBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PopupBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller4 = lv_roller_create(ui_PopupBox);
    lv_roller_set_options(ui_Roller4,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller4, 148);
    lv_obj_set_width(ui_Roller4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller4, -1);
    lv_obj_set_y(ui_Roller4, -1);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_letter_space(ui_Roller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(ui_Roller4, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller4, 15, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller4, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_PopupBox);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -18);
    lv_obj_set_y(ui_Label37, -3);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, ":");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller5 = lv_roller_create(ui_PopupBox);
    lv_roller_set_options(ui_Roller5,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller5, 150);
    lv_obj_set_width(ui_Roller5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller5, 13);
    lv_obj_set_y(ui_Roller5, -1);
    lv_obj_set_align(ui_Roller5, LV_ALIGN_CENTER);
    lv_obj_set_style_text_letter_space(ui_Roller5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(ui_Roller5, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller5, 15, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller5, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button21 = lv_btn_create(ui_PopupBox);
    lv_obj_set_width(ui_Button21, 27);
    lv_obj_set_height(ui_Button21, 42);
    lv_obj_set_x(ui_Button21, 65);
    lv_obj_set_y(ui_Button21, -52);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_PopupBox);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 66);
    lv_obj_set_y(ui_Label38, -19);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "BACK");

    ui_Button22 = lv_btn_create(ui_PopupBox);
    lv_obj_set_width(ui_Button22, 28);
    lv_obj_set_height(ui_Button22, 42);
    lv_obj_set_x(ui_Button22, 66);
    lv_obj_set_y(ui_Button22, 47);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_PopupBox);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 66);
    lv_obj_set_y(ui_Label39, 14);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "ADD");

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmSwitch1, ui_event_AlarmSwitch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmSwitch2, ui_event_AlarmSwitch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmSwitch3, ui_event_AlarmSwitch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmSwitch4, ui_event_AlarmSwitch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmSwitch5, ui_event_AlarmSwitch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label7 = NULL;
    ui_Button5 = NULL;
    ui_Label8 = NULL;
    ui_AlarmListPanel = NULL;
    ui_AlarmCard1 = NULL;
    ui_AlarmTime1 = NULL;
    ui_Button15 = NULL;
    ui_Label27 = NULL;
    ui_AlarmSwitch1 = NULL;
    ui_AlarmCard2 = NULL;
    ui_AlarmTime2 = NULL;
    ui_Button17 = NULL;
    ui_Label30 = NULL;
    ui_AlarmSwitch2 = NULL;
    ui_AlarmCard3 = NULL;
    ui_AlarmTime3 = NULL;
    ui_Button18 = NULL;
    ui_Label32 = NULL;
    ui_AlarmSwitch3 = NULL;
    ui_AlarmCard4 = NULL;
    ui_AlarmTime4 = NULL;
    ui_Button19 = NULL;
    ui_Label34 = NULL;
    ui_AlarmSwitch4 = NULL;
    ui_AlarmCard5 = NULL;
    ui_AlarmTime5 = NULL;
    ui_Button20 = NULL;
    ui_Label36 = NULL;
    ui_AlarmSwitch5 = NULL;
    ui_Button16 = NULL;
    ui_Label28 = NULL;
    ui_PopupAdd = NULL;
    ui_PopupBox = NULL;
    ui_Roller4 = NULL;
    ui_Label37 = NULL;
    ui_Roller5 = NULL;
    ui_Button21 = NULL;
    ui_Label38 = NULL;
    ui_Button22 = NULL;
    ui_Label39 = NULL;

}
