// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel3;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern void ui_event_Image9(lv_event_t * e);
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

