// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label7;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_AlarmListPanel;
extern lv_obj_t * ui_AlarmCard1;
extern lv_obj_t * ui_AlarmTime1;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label27;
extern void ui_event_AlarmSwitch1(lv_event_t * e);
extern lv_obj_t * ui_AlarmSwitch1;
extern lv_obj_t * ui_AlarmCard2;
extern lv_obj_t * ui_AlarmTime2;
extern void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label30;
extern void ui_event_AlarmSwitch2(lv_event_t * e);
extern lv_obj_t * ui_AlarmSwitch2;
extern lv_obj_t * ui_AlarmCard3;
extern lv_obj_t * ui_AlarmTime3;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label32;
extern void ui_event_AlarmSwitch3(lv_event_t * e);
extern lv_obj_t * ui_AlarmSwitch3;
extern lv_obj_t * ui_AlarmCard4;
extern lv_obj_t * ui_AlarmTime4;
extern void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label34;
extern void ui_event_AlarmSwitch4(lv_event_t * e);
extern lv_obj_t * ui_AlarmSwitch4;
extern lv_obj_t * ui_AlarmCard5;
extern lv_obj_t * ui_AlarmTime5;
extern void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label36;
extern void ui_event_AlarmSwitch5(lv_event_t * e);
extern lv_obj_t * ui_AlarmSwitch5;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_PopupAdd;
extern lv_obj_t * ui_PopupBox;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Roller5;
extern void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label38;
extern void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label39;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

