// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_SwitchWIFI = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_DropdownWifi = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen8_screen_init);
    }
}

void ui_event_SwitchWIFI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onWifiSwitchToggle(e);
    }
}

void ui_event_DropdownWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WifiDropdownChanged(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PasswordBtnClicked(e);
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen4_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifirefresh(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 62);
    lv_obj_set_height(ui_Button2, 31);
    lv_obj_set_x(ui_Button2, -62);
    lv_obj_set_y(ui_Button2, -100);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -63);
    lv_obj_set_y(ui_Label2, -124);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "BACK");

    ui_SwitchWIFI = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_SwitchWIFI, 60);
    lv_obj_set_height(ui_SwitchWIFI, 30);
    lv_obj_set_x(ui_SwitchWIFI, 50);
    lv_obj_set_y(ui_SwitchWIFI, -100);
    lv_obj_set_align(ui_SwitchWIFI, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 50);
    lv_obj_set_y(ui_Label3, -126);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WIFI ON/OFF");

    ui_DropdownWifi = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_text(ui_DropdownWifi, "WIFI SSID");
    lv_obj_set_width(ui_DropdownWifi, 236);
    lv_obj_set_height(ui_DropdownWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownWifi, 1);
    lv_obj_set_y(ui_DropdownWifi, -54);
    lv_obj_set_align(ui_DropdownWifi, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DropdownWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_DropdownWifi), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_DropdownWifi), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownWifi), &ui_font_Font1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button4, 97);
    lv_obj_set_height(ui_Button4, 31);
    lv_obj_set_x(ui_Button4, -65);
    lv_obj_set_y(ui_Button4, 117);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -63);
    lv_obj_set_y(ui_Label4, 117);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PASSWORD");

    ui_Button6 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button6, 97);
    lv_obj_set_height(ui_Button6, 31);
    lv_obj_set_x(ui_Button6, 61);
    lv_obj_set_y(ui_Button6, 117);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 60);
    lv_obj_set_y(ui_Label6, 116);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "REFRESH");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchWIFI, ui_event_SwitchWIFI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownWifi, ui_event_DropdownWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Button2 = NULL;
    ui_Label2 = NULL;
    ui_SwitchWIFI = NULL;
    ui_Label3 = NULL;
    ui_DropdownWifi = NULL;
    ui_Button4 = NULL;
    ui_Label4 = NULL;
    ui_Button6 = NULL;
    ui_Label6 = NULL;

}
