// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_preface = NULL;
lv_obj_t * ui_enter = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_uiPopupAlert = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Button23 = NULL;
lv_obj_t * ui_Label41 = NULL;
// event funtions
void ui_event_enter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onSyncTimeClicked(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen8_screen_init);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPopupAlert, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_preface = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_preface, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_preface, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_preface, -4);
    lv_obj_set_y(ui_preface, -120);
    lv_obj_set_align(ui_preface, LV_ALIGN_CENTER);
    lv_label_set_text(ui_preface, "Welcome to Watch");

    ui_enter = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_enter, 100);
    lv_obj_set_height(ui_enter, 50);
    lv_obj_set_x(ui_enter, 2);
    lv_obj_set_y(ui_enter, -9);
    lv_obj_set_align(ui_enter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_enter, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_enter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -5);
    lv_obj_set_y(ui_time, -80);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "TIME");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 4);
    lv_obj_set_y(ui_Button1, 74);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 4);
    lv_obj_set_y(ui_Label1, 33);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "funtions");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, -41);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SYNC");

    ui_uiPopupAlert = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPopupAlert, lv_pct(100));
    lv_obj_set_height(ui_uiPopupAlert, lv_pct(100));
    lv_obj_set_x(ui_uiPopupAlert, 1);
    lv_obj_set_y(ui_uiPopupAlert, 0);
    lv_obj_set_align(ui_uiPopupAlert, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPopupAlert, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPopupAlert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPopupAlert, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPopupAlert, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_uiPopupAlert);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 18);
    lv_obj_set_y(ui_Label40, -79);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "RING.....");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button23 = lv_btn_create(ui_uiPopupAlert);
    lv_obj_set_width(ui_Button23, 100);
    lv_obj_set_height(ui_Button23, 50);
    lv_obj_set_x(ui_Button23, 1);
    lv_obj_set_y(ui_Button23, 26);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_uiPopupAlert);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 3);
    lv_obj_set_y(ui_Label41, 28);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "I KNOW");

    lv_obj_add_event_cb(ui_enter, ui_event_enter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_preface = NULL;
    ui_enter = NULL;
    ui_time = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;
    ui_Label5 = NULL;
    ui_uiPopupAlert = NULL;
    ui_Label40 = NULL;
    ui_Button23 = NULL;
    ui_Label41 = NULL;

}
