// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen11 = NULL;
lv_obj_t * ui_TimerSetGroup = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Roller2 = NULL;
lv_obj_t * ui_Roller3 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_STARTBUT = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Button27 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_TimerRunGroup = NULL;
lv_obj_t * ui_TimerArc = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Button24 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_Button25 = NULL;
lv_obj_t * ui_LabelTimerStop = NULL;
lv_obj_t * ui_Button26 = NULL;
lv_obj_t * ui_Label44 = NULL;
// event funtions
void ui_event_Screen11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_Screen2_screen_init);
    }
}

void ui_event_STARTBUT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onTimerStartClicked(e);
    }
}

void ui_event_Button27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onTimerCheckClicked(e);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onTimerBackClicked(e);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onTimerStopClicked(e);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onTimerResetClicked(e);
    }
}

// build funtions

void ui_Screen11_screen_init(void)
{
    ui_Screen11 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen11, lv_color_hex(0xF0F4F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerSetGroup = lv_obj_create(ui_Screen11);
    lv_obj_set_width(ui_TimerSetGroup, lv_pct(100));
    lv_obj_set_height(ui_TimerSetGroup, lv_pct(100));
    lv_obj_set_x(ui_TimerSetGroup, -1);
    lv_obj_set_y(ui_TimerSetGroup, 3);
    lv_obj_set_align(ui_TimerSetGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimerSetGroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimerSetGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimerSetGroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_TimerSetGroup);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -76);
    lv_obj_set_y(ui_Label26, -118);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "SAND");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_TimerSetGroup);
    lv_roller_set_options(ui_Roller1,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, -82);
    lv_obj_set_y(ui_Roller1, -7);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Label29 = lv_label_create(ui_TimerSetGroup);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -41);
    lv_obj_set_y(ui_Label29, -9);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, ":");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_TimerSetGroup);
    lv_roller_set_options(ui_Roller2,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller2, 100);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, -1);
    lv_obj_set_y(ui_Roller2, -7);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    ui_Roller3 = lv_roller_create(ui_TimerSetGroup);
    lv_roller_set_options(ui_Roller3,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller3, 100);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller3, 74);
    lv_obj_set_y(ui_Roller3, -7);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    ui_Label31 = lv_label_create(ui_TimerSetGroup);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 36);
    lv_obj_set_y(ui_Label31, -9);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, ":");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STARTBUT = lv_btn_create(ui_TimerSetGroup);
    lv_obj_set_width(ui_STARTBUT, 100);
    lv_obj_set_height(ui_STARTBUT, 33);
    lv_obj_set_x(ui_STARTBUT, -1);
    lv_obj_set_y(ui_STARTBUT, 93);
    lv_obj_set_align(ui_STARTBUT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_STARTBUT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_STARTBUT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_STARTBUT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTBUT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_STARTBUT);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -1);
    lv_obj_set_y(ui_Label35, 0);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "START");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_btn_create(ui_TimerSetGroup);
    lv_obj_set_width(ui_Button27, 91);
    lv_obj_set_height(ui_Button27, 36);
    lv_obj_set_x(ui_Button27, 59);
    lv_obj_set_y(ui_Button27, -117);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "CHECK");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerRunGroup = lv_obj_create(ui_Screen11);
    lv_obj_set_width(ui_TimerRunGroup, lv_pct(100));
    lv_obj_set_height(ui_TimerRunGroup, lv_pct(100));
    lv_obj_set_align(ui_TimerRunGroup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimerRunGroup, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TimerRunGroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimerRunGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimerRunGroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerArc = lv_arc_create(ui_TimerRunGroup);
    lv_obj_set_width(ui_TimerArc, 150);
    lv_obj_set_height(ui_TimerArc, 150);
    lv_obj_set_x(ui_TimerArc, -3);
    lv_obj_set_y(ui_TimerArc, -20);
    lv_obj_set_align(ui_TimerArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimerArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_TimerArc, 50);
    lv_arc_set_bg_angles(ui_TimerArc, 0, 360);
    lv_arc_set_rotation(ui_TimerArc, 1);

    lv_obj_set_style_bg_color(ui_TimerArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimerArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_TimerArc);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "00:00:00");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button24 = lv_btn_create(ui_TimerRunGroup);
    lv_obj_set_width(ui_Button24, 62);
    lv_obj_set_height(ui_Button24, 36);
    lv_obj_set_x(ui_Button24, -85);
    lv_obj_set_y(ui_Button24, -119);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "BACK");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button25 = lv_btn_create(ui_TimerRunGroup);
    lv_obj_set_width(ui_Button25, 82);
    lv_obj_set_height(ui_Button25, 45);
    lv_obj_set_x(ui_Button25, -68);
    lv_obj_set_y(ui_Button25, 106);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimerStop = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_LabelTimerStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimerStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTimerStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimerStop, "STOP");
    lv_obj_set_style_text_color(ui_LabelTimerStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimerStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button26 = lv_btn_create(ui_TimerRunGroup);
    lv_obj_set_width(ui_Button26, 82);
    lv_obj_set_height(ui_Button26, 45);
    lv_obj_set_x(ui_Button26, 65);
    lv_obj_set_y(ui_Button26, 106);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Button26);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "RESET");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_STARTBUT, ui_event_STARTBUT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen11, ui_event_Screen11, LV_EVENT_ALL, NULL);

}

void ui_Screen11_screen_destroy(void)
{
    if(ui_Screen11) lv_obj_del(ui_Screen11);

    // NULL screen variables
    ui_Screen11 = NULL;
    ui_TimerSetGroup = NULL;
    ui_Label26 = NULL;
    ui_Roller1 = NULL;
    ui_Label29 = NULL;
    ui_Roller2 = NULL;
    ui_Roller3 = NULL;
    ui_Label31 = NULL;
    ui_STARTBUT = NULL;
    ui_Label35 = NULL;
    ui_Button27 = NULL;
    ui_Label43 = NULL;
    ui_TimerRunGroup = NULL;
    ui_TimerArc = NULL;
    ui_Label33 = NULL;
    ui_Button24 = NULL;
    ui_Label42 = NULL;
    ui_Button25 = NULL;
    ui_LabelTimerStop = NULL;
    ui_Button26 = NULL;
    ui_Label44 = NULL;

}
