// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREENCALC_H
#define UI_SCREENCALC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenCalc
extern void ui_ScreenCalc_screen_init(void);
extern void ui_ScreenCalc_screen_destroy(void);
extern lv_obj_t * ui_ScreenCalc;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Panel1;
extern void ui_event_Label46(lv_event_t * e);
extern lv_obj_t * ui_Label46;
extern void ui_event_Label47(lv_event_t * e);
extern lv_obj_t * ui_Label47;
extern void ui_event_Label48(lv_event_t * e);
extern lv_obj_t * ui_Label48;
extern void ui_event_Label49(lv_event_t * e);
extern lv_obj_t * ui_Label49;
extern void ui_event_Label50(lv_event_t * e);
extern lv_obj_t * ui_Label50;
extern void ui_event_Label51(lv_event_t * e);
extern lv_obj_t * ui_Label51;
extern void ui_event_Label52(lv_event_t * e);
extern lv_obj_t * ui_Label52;
extern void ui_event_Label53(lv_event_t * e);
extern lv_obj_t * ui_Label53;
extern void ui_event_Label54(lv_event_t * e);
extern lv_obj_t * ui_Label54;
extern void ui_event_Label55(lv_event_t * e);
extern lv_obj_t * ui_Label55;
extern void ui_event_Label56(lv_event_t * e);
extern lv_obj_t * ui_Label56;
extern void ui_event_Label57(lv_event_t * e);
extern lv_obj_t * ui_Label57;
extern void ui_event_Label58(lv_event_t * e);
extern lv_obj_t * ui_Label58;
extern void ui_event_Label59(lv_event_t * e);
extern lv_obj_t * ui_Label59;
extern void ui_event_Label60(lv_event_t * e);
extern lv_obj_t * ui_Label60;
extern void ui_event_Label61(lv_event_t * e);
extern lv_obj_t * ui_Label61;
extern void ui_event_Label62(lv_event_t * e);
extern lv_obj_t * ui_Label62;
extern void ui_event_Label63(lv_event_t * e);
extern lv_obj_t * ui_Label63;
extern void ui_event_Label64(lv_event_t * e);
extern lv_obj_t * ui_Label64;
extern void ui_event_Label65(lv_event_t * e);
extern lv_obj_t * ui_Label65;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

