// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen9 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_CITY = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen8_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CheckWeather(e);
    }
}

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -3);
    lv_obj_set_y(ui_Label14, -120);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "CITYNAME");

    ui_CITY = lv_textarea_create(ui_Screen9);
    lv_obj_set_width(ui_CITY, 231);
    lv_obj_set_height(ui_CITY, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_CITY, 5);
    lv_obj_set_y(ui_CITY, -88);
    lv_obj_set_align(ui_CITY, LV_ALIGN_LEFT_MID);
    lv_textarea_set_placeholder_text(ui_CITY, "请输入城市名字");
    lv_textarea_set_one_line(ui_CITY, true);
    lv_obj_set_style_text_color(ui_CITY, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CITY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CITY, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_Button3, 81);
    lv_obj_set_height(ui_Button3, 31);
    lv_obj_set_x(ui_Button3, -73);
    lv_obj_set_y(ui_Button3, -40);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -72);
    lv_obj_set_y(ui_Label18, -38);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "BACK");

    ui_Button7 = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_Button7, 74);
    lv_obj_set_height(ui_Button7, 29);
    lv_obj_set_x(ui_Button7, 73);
    lv_obj_set_y(ui_Button7, -39);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 73);
    lv_obj_set_y(ui_Label20, -38);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "CHECK");

    ui_Keyboard2 = lv_keyboard_create(ui_Screen9);
    lv_obj_set_width(ui_Keyboard2, 233);
    lv_obj_set_height(ui_Keyboard2, 155);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 61);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_CITY);

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;
    ui_Label14 = NULL;
    ui_CITY = NULL;
    ui_Button3 = NULL;
    ui_Label18 = NULL;
    ui_Button7 = NULL;
    ui_Label20 = NULL;
    ui_Keyboard2 = NULL;

}
