// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen3_screen_init);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiConnectAction(e);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -7);
    lv_obj_set_y(ui_Label9, -129);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "WIFINAME");

    ui_TextArea1 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea1, 236);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_TextArea1, 2);
    lv_obj_set_y(ui_TextArea1, -99);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_TextArea1, 64);
    lv_textarea_set_placeholder_text(ui_TextArea1, "请输入密码");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0x110F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen4);
    lv_obj_set_width(ui_Keyboard1, 236);
    lv_obj_set_height(ui_Keyboard1, 147);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 63);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Button8 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button8, 76);
    lv_obj_set_height(ui_Button8, 30);
    lv_obj_set_x(ui_Button8, -77);
    lv_obj_set_y(ui_Button8, -39);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -76);
    lv_obj_set_y(ui_Label10, -39);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "CANCEL");

    ui_Button9 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button9, 77);
    lv_obj_set_height(ui_Button9, 31);
    lv_obj_set_x(ui_Button9, 71);
    lv_obj_set_y(ui_Button9, -39);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 71);
    lv_obj_set_y(ui_Label11, -39);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "CONNECT");

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Label9 = NULL;
    ui_TextArea1 = NULL;
    ui_Keyboard1 = NULL;
    ui_Button8 = NULL;
    ui_Label10 = NULL;
    ui_Button9 = NULL;
    ui_Label11 = NULL;

}
