// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen13 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label70 = NULL;
lv_obj_t * ui_Label71 = NULL;
lv_obj_t * ui_Label72 = NULL;
lv_obj_t * ui_Button30 = NULL;
// event funtions
void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen8_screen_init);
    }
}

// build funtions

void ui_Screen13_screen_init(void)
{
    ui_Screen13 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_Screen13);
    lv_img_set_src(ui_Image11, &ui_img_880976351);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, 1);
    lv_obj_set_y(ui_Image11, -11);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Image11);
    lv_img_set_src(ui_Image10, &ui_img_1999394341);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, -2);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Screen13);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, -124);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "N");

    ui_Label70 = lv_label_create(ui_Screen13);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label70, 111);
    lv_obj_set_y(ui_Label70, -10);
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "E");

    ui_Label71 = lv_label_create(ui_Screen13);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label71, -109);
    lv_obj_set_y(ui_Label71, -9);
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "W");

    ui_Label72 = lv_label_create(ui_Screen13);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label72, 1);
    lv_obj_set_y(ui_Label72, 105);
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "S");

    ui_Button30 = lv_btn_create(ui_Screen13);
    lv_obj_set_width(ui_Button30, 72);
    lv_obj_set_height(ui_Button30, 23);
    lv_obj_set_x(ui_Button30, -77);
    lv_obj_set_y(ui_Button30, 122);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);

}

void ui_Screen13_screen_destroy(void)
{
    if(ui_Screen13) lv_obj_del(ui_Screen13);

    // NULL screen variables
    ui_Screen13 = NULL;
    ui_Image11 = NULL;
    ui_Image10 = NULL;
    ui_Label25 = NULL;
    ui_Label70 = NULL;
    ui_Label71 = NULL;
    ui_Label72 = NULL;
    ui_Button30 = NULL;

}
