// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREEN13_H
#define UI_SCREEN13_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen13
extern void ui_Screen13_screen_init(void);
extern void ui_Screen13_screen_destroy(void);
extern lv_obj_t * ui_Screen13;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Label72;
extern void ui_event_Button30(lv_event_t * e);
extern lv_obj_t * ui_Button30;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

