// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_SCREEN11_H
#define UI_SCREEN11_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen11
extern void ui_Screen11_screen_init(void);
extern void ui_Screen11_screen_destroy(void);
extern void ui_event_Screen11(lv_event_t * e);
extern lv_obj_t * ui_Screen11;
extern lv_obj_t * ui_TimerSetGroup;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Label31;
extern void ui_event_STARTBUT(lv_event_t * e);
extern lv_obj_t * ui_STARTBUT;
extern lv_obj_t * ui_Label35;
extern void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_TimerRunGroup;
extern lv_obj_t * ui_TimerArc;
extern lv_obj_t * ui_Label33;
extern void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label42;
extern void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_LabelTimerStop;
extern void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label44;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

