// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_Screen12 = NULL;
lv_obj_t * ui_PanelAIChat = NULL;
lv_obj_t * ui_LabelAIText = NULL;
lv_obj_t * ui_Button29 = NULL;
lv_obj_t * ui_Label68 = NULL;
lv_obj_t * ui_BtnNewChat = NULL;
lv_obj_t * ui_Label69 = NULL;
// event funtions
void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 50, &ui_Screen8_screen_init);
    }
}

void ui_event_BtnNewChat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onNewChatClicked(e);
    }
}

// build funtions

void ui_Screen12_screen_init(void)
{
    ui_Screen12 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelAIChat = lv_obj_create(ui_Screen12);
    lv_obj_set_width(ui_PanelAIChat, lv_pct(100));
    lv_obj_set_height(ui_PanelAIChat, lv_pct(60));
    lv_obj_set_x(ui_PanelAIChat, 0);
    lv_obj_set_y(ui_PanelAIChat, -43);
    lv_obj_set_align(ui_PanelAIChat, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelAIChat, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_PanelAIChat, lv_color_hex(0xB0AAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAIChat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelAIChat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAIText = lv_label_create(ui_PanelAIChat);
    lv_obj_set_width(ui_LabelAIText, lv_pct(100));
    lv_obj_set_height(ui_LabelAIText, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelAIText, "欢迎使用deepseek");
    lv_obj_set_style_text_font(ui_LabelAIText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button29 = lv_btn_create(ui_Screen12);
    lv_obj_set_width(ui_Button29, 77);
    lv_obj_set_height(ui_Button29, 34);
    lv_obj_set_x(ui_Button29, -70);
    lv_obj_set_y(ui_Button29, 96);
    lv_obj_set_align(ui_Button29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button29, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button29, lv_color_hex(0x594D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_Button29);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "BACK");

    ui_BtnNewChat = lv_btn_create(ui_Screen12);
    lv_obj_set_width(ui_BtnNewChat, 71);
    lv_obj_set_height(ui_BtnNewChat, 35);
    lv_obj_set_x(ui_BtnNewChat, 65);
    lv_obj_set_y(ui_BtnNewChat, 95);
    lv_obj_set_align(ui_BtnNewChat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNewChat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNewChat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNewChat, lv_color_hex(0x594D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNewChat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label69 = lv_label_create(ui_BtnNewChat);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 1);
    lv_obj_set_y(ui_Label69, 0);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "NEW");

    lv_obj_add_event_cb(ui_Button29, ui_event_Button29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNewChat, ui_event_BtnNewChat, LV_EVENT_ALL, NULL);

}

void ui_Screen12_screen_destroy(void)
{
    if(ui_Screen12) lv_obj_del(ui_Screen12);

    // NULL screen variables
    ui_Screen12 = NULL;
    ui_PanelAIChat = NULL;
    ui_LabelAIText = NULL;
    ui_Button29 = NULL;
    ui_Label68 = NULL;
    ui_BtnNewChat = NULL;
    ui_Label69 = NULL;

}
