// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_uiScreenCalendar = NULL;
lv_obj_t * ui_Calendar1 = NULL;
// event funtions
void ui_event_uiScreenCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen8_screen_init);
    }
}

// build funtions

void ui_uiScreenCalendar_screen_init(void)
{
    ui_uiScreenCalendar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_uiScreenCalendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_uiScreenCalendar);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 230);
    lv_obj_set_height(ui_Calendar1, 240);
    lv_obj_set_x(ui_Calendar1, 1);
    lv_obj_set_y(ui_Calendar1, -6);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_set_style_border_width(ui_Calendar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uiScreenCalendar, ui_event_uiScreenCalendar, LV_EVENT_ALL, NULL);

}

void ui_uiScreenCalendar_screen_destroy(void)
{
    if(ui_uiScreenCalendar) lv_obj_del(ui_uiScreenCalendar);

    // NULL screen variables
    ui_uiScreenCalendar = NULL;
    ui_Calendar1 = NULL;

}
