// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_UISCREENHEALTH_H
#define UI_UISCREENHEALTH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenHealth
extern void ui_uiScreenHealth_screen_init(void);
extern void ui_uiScreenHealth_screen_destroy(void);
extern lv_obj_t * ui_uiScreenHealth;
extern lv_obj_t * ui_LabelBPM;
extern lv_obj_t * ui_LabelSpO2;
extern void ui_event_SwitchHealth(lv_event_t * e);
extern lv_obj_t * ui_SwitchHealth;
extern void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label67;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

