// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#include "../ui.h"

lv_obj_t * ui_uiScreenHealth = NULL;
lv_obj_t * ui_LabelBPM = NULL;
lv_obj_t * ui_LabelSpO2 = NULL;
lv_obj_t * ui_SwitchHealth = NULL;
lv_obj_t * ui_Button28 = NULL;
lv_obj_t * ui_Label66 = NULL;
lv_obj_t * ui_Label67 = NULL;
// event funtions
void ui_event_SwitchHealth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onHealthSwitchChanged(e);
    }
}

void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 50, &ui_Screen8_screen_init);
    }
}

// build funtions

void ui_uiScreenHealth_screen_init(void)
{
    ui_uiScreenHealth = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_uiScreenHealth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBPM = lv_label_create(ui_uiScreenHealth);
    lv_obj_set_width(ui_LabelBPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBPM, -52);
    lv_obj_set_y(ui_LabelBPM, -30);
    lv_obj_set_align(ui_LabelBPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBPM, "---");
    lv_obj_set_style_text_font(ui_LabelBPM, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpO2 = lv_label_create(ui_uiScreenHealth);
    lv_obj_set_width(ui_LabelSpO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpO2, 48);
    lv_obj_set_y(ui_LabelSpO2, -30);
    lv_obj_set_align(ui_LabelSpO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpO2, "---%");
    lv_obj_set_style_text_font(ui_LabelSpO2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchHealth = lv_switch_create(ui_uiScreenHealth);
    lv_obj_set_width(ui_SwitchHealth, 50);
    lv_obj_set_height(ui_SwitchHealth, 25);
    lv_obj_set_x(ui_SwitchHealth, 67);
    lv_obj_set_y(ui_SwitchHealth, -99);
    lv_obj_set_align(ui_SwitchHealth, LV_ALIGN_CENTER);

    ui_Button28 = lv_btn_create(ui_uiScreenHealth);
    lv_obj_set_width(ui_Button28, 66);
    lv_obj_set_height(ui_Button28, 33);
    lv_obj_set_x(ui_Button28, -60);
    lv_obj_set_y(ui_Button28, -98);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "BACK");
    lv_obj_set_style_text_color(ui_Label66, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label66, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_uiScreenHealth);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, 68);
    lv_obj_set_y(ui_Label67, -71);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "TEST ON/OFF");

    lv_obj_add_event_cb(ui_SwitchHealth, ui_event_SwitchHealth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);

}

void ui_uiScreenHealth_screen_destroy(void)
{
    if(ui_uiScreenHealth) lv_obj_del(ui_uiScreenHealth);

    // NULL screen variables
    ui_uiScreenHealth = NULL;
    ui_LabelBPM = NULL;
    ui_LabelSpO2 = NULL;
    ui_SwitchHealth = NULL;
    ui_Button28 = NULL;
    ui_Label66 = NULL;
    ui_Label67 = NULL;

}
