// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_UISCREENCALENDAR_H
#define UI_UISCREENCALENDAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenCalendar
extern void ui_uiScreenCalendar_screen_init(void);
extern void ui_uiScreenCalendar_screen_destroy(void);
extern void ui_event_uiScreenCalendar(lv_event_t * e);
extern lv_obj_t * ui_uiScreenCalendar;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

